export type TimeEntryUpdate = {
  event_id: number;
  created_at: string;
  creator_id: number;
  metadata: {
    action: "updated";
    event_user_id: string;
    model: "time_entry";
    model_owner_id: string;
    path: string;
    project_id: string;
    project_is_private: string;
    request_body: string;
    request_type: string;
    time_entry_id: string;
    workspace_id: string;
  };
  payload: {
    at: string;
    billable: boolean;
    description: string;
    duration: number;
    duronly: boolean;
    id: number;
    pid: number;
    project_id: number;
    server_deleted_at: null;
    start: string;
    stop: string | null;
    tag_ids: number[];
    tags: string[];
    task_id: null;
    uid: number;
    user_id: number;
    wid: number;
    workspace_id: number;
  };
  subscription_id: number;
  timestamp: string;
  url_callback: string;
};
