openapi: 3.0.0
info:
  title: Toggl API
  version: 1.0.0
servers:
  - url: https://api.track.toggl.com/api/v9/
components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
security:
  - basicAuth: []
paths:
  /me:
    $ref: "routes/me.yaml"
  /me/clients:
    $ref: "routes/me/clients.yaml"
  /me/features:
    $ref: "routes/me/features.yaml"
  /me/location:
    $ref: "routes/me/location.yaml"
  /me/logged:
    $ref: "routes/me/logged.yaml"
  /me/organizations:
    $ref: "routes/me/organizations.yaml"
  /me/projects:
    $ref: "routes/me/projects.yaml"
  /me/projects/paginated:
    $ref: "routes/me/projects/paginated.yaml"
  /me/tags:
    $ref: "routes/me/tags.yaml"
  /me/tasks:
    $ref: "routes/me/tasks.yaml"
  /me/track_reminders:
    $ref: "routes/me/track_reminders.yaml"
  /me/web-timer:
    $ref: "routes/me/web-timer.yaml"
  /me/workspaces:
    $ref: "routes/me/workspaces.yaml"
  /me/preferences:
    $ref: "routes/me/preferences.yaml"
  /me/preferences/{client}:
    $ref: "routes/me/preferences/{client}.yaml"
  /workspaces/{workspace_id}/preferences:
    $ref: "routes/workspaces/{workspace_id}/preferences.yaml"
  /me/reset_token:
    $ref: "routes/me/reset_token.yaml"
