type EnvKey =
  | "BASEROW_DATABASE_TOKEN"
  | "BASEROW_DOMAIN"
  | "BM_AUTHS"
  | "DYNALIST_TOKEN"
  | "GITHUB_TOKEN"
  | "MAILGUN_API_KEY"
  | "MAILGUN_DOMAIN"
  | "NOTION_API_KEY"
  | "NOTION_DATABASE_ID_TODOS"
  | "NOTION_DATABASE_ID_TR_CARDS"
  | "OPENAI_PROMPT"
  | "OPENAI_SECRET_KEY"
  | "SENTRY_DSN"
  | "TASKRATCHET_API_TOKEN"
  | "TASKRATCHET_USER_ID"
  | "TELEGRAM_ALLOWED_USER"
  | "TELEGRAM_API_TOKEN"
  | "TELEGRAM_CHAT_ID"
  | "TELEGRAM_WEBHOOK_TOKEN"
  | "TOGGL_API_TOKEN"
  | "TOGGL_CLIENT_AV"
  | "TOGGL_SIGNING_SECRET"
  | "TRELLO_API_KEY"
  | "TRELLO_API_TOKEN"
  | "TRELLO_INC_BOARD_ID"
  | "TRELLO_INC_INBOX_LIST_ID";

export default function env(key: EnvKey): string | undefined {
  return process.env[key];
}
