services:
  - type: web
    name: automations
    runtime: node
    region: ohio
    plan: starter
    buildCommand: pnpm install && pnpm build
    startCommand: pnpm start
    envVars:
      - key: SKIP_INSTALL_DEPS
        value: "true"
