export const SELF_CARE = [
  "Take a walk",
  "Take a nap",
  "Take a bath",
  "Take a break",
  "Take a deep breath",
  "Box breathing",
  "Take a shower",
  "Jumping jacks",
  "Do some pushups",
  "Do some situps",
  "Do some squats",
  "Do some crunches",
  "Listen to some music",
  "Listen to a podcast",
  "Take out the trash",
  "Do the dishes",
  "Clean the kitchen",
  "Clean the bathroom",
  "Clean the living room",
  "Clean the bedroom",
  "Clean the office",
  "Make the bed",
  "Do some laundry",
  "Text a friend",
  "Call a friend",
  "Call a family member",
  "Call your mom",
  "Call your dad",
  "Call your sibling",
  "Meditate",
  "Stretch",
  "Do a short workout",
  "Read a book",
  "Read a short story",
  "Message a friend on Discord",
  "Email a friend",
  "Work on a puzzle",
  "Go outside",
  "Go for a run",
  "Go to the park",
  "Go to the library",
  "Go to the grocery store",
  "Make a list",
  "Make a plan",
  "Ask for help",
  "Do fear setting",
  "Do a brain dump",
  "Write a letter",
  "Write a poem",
  "Write a short story",
  "Write a blog post",
];
