name: Hourly
on:
  push:
  schedule:
    - cron: "0 * * * *"
jobs:
  shell:
    runs-on: ubuntu-latest
    steps:
      - run: date
      - uses: actions/checkout@v3
      - run: sudo apt-get update && sudo apt-get install jq
      - run: ./scripts/techtainment.sh
        env:
          AUTH_TOKEN: ${{ secrets.BM_TOKEN }}
          USERNAME: ${{ secrets.BM_USER }}
  node:
    runs-on: ubuntu-latest
    steps:
      - run: date
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7
      - name: Use Node.js 16.15.0
        uses: actions/setup-node@v2
        with:
          node-version: 16.15.0
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install
      - name: Run gross
        run: pnpm ts-node ./src/gross.ts
        env:
          AUTH_TOKEN: ${{ secrets.BM_TOKEN }}
          USERNAME: ${{ secrets.BM_USER }}
          TOGGL_API_TOKEN: ${{ secrets.TOGGL_API_TOKEN }}
          GROSS_TOGGL_LABELS: ${{ secrets.GROSS_TOGGL_LABELS }}
          GROSS_TOGGL_PROJECTS: ${{ secrets.GROSS_TOGGL_PROJECTS }}
          GROSS_TOGGL_RATES: ${{ secrets.GROSS_TOGGL_RATES }}
