name: Hourly
on:
  push:
  schedule:
    - cron: '0 * * * *'
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt-get update && sudo apt-get install jq
      - run: ./scripts/techtainment.sh
        env:
          AUTH_TOKEN: ${{ secrets.BM_TOKEN }}
          USERNAME: ${{ secrets.BM_USER }}