name: Merge
on:
  push:
    branches:
      - "main"
env:
  NODE_VERSION: 16
jobs:
  auto:
    runs-on: ubuntu-latest
    steps:
      - name: Post to Beeminder goal "auto"
        run: |
          curl -X POST https://www.beeminder.com/api/v1/users/${{ secrets.BM_USER }}/goals/auto/datapoints.json \
            -d auth_token=${{ secrets.BM_TOKEN }} \
            -d requestid=${{ github.sha }} \
            -d value=1 \
            -d comment="${{ github.event.head_commit.message }} (${{ github.repository }}:${{ github.sha }})"
  deploy:
    runs-on: ubuntu-latest
    env:
      GOOGLE_APPLICATION_CREDENTIALS: ./service-account.json
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install
      - name: Install Firebase CLI
        run: npm install -g firebase-tools@11.18.0
      - name: Create service account json file
        run: echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}" > service-account.json
      - name: Deploy
        run: firebase deploy --only functions
