name: Beeminder Exercise >> Techtainment
on:
  schedule:
    - cron: '0 * * * *' # hourly
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: apt update && apt install jq
      - run: ./scripts/techtainment.sh